title: StreetTreeFutures
logo: docs/assets/STF - Coloured (Transparent).png
description: A research project
#show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
